require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SpidersController do

  # This should return the minimal set of attributes required to create a valid
  # Spider. As you add validations to Spider, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all spiders as @spiders" do
      spider = Spider.create! valid_attributes
      get :index
      assigns(:spiders).should eq([spider])
    end
  end

  describe "GET show" do
    it "assigns the requested spider as @spider" do
      spider = Spider.create! valid_attributes
      get :show, :id => spider.id.to_s
      assigns(:spider).should eq(spider)
    end
  end

  describe "GET new" do
    it "assigns a new spider as @spider" do
      get :new
      assigns(:spider).should be_a_new(Spider)
    end
  end

  describe "GET edit" do
    it "assigns the requested spider as @spider" do
      spider = Spider.create! valid_attributes
      get :edit, :id => spider.id.to_s
      assigns(:spider).should eq(spider)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Spider" do
        expect {
          post :create, :spider => valid_attributes
        }.to change(Spider, :count).by(1)
      end

      it "assigns a newly created spider as @spider" do
        post :create, :spider => valid_attributes
        assigns(:spider).should be_a(Spider)
        assigns(:spider).should be_persisted
      end

      it "redirects to the created spider" do
        post :create, :spider => valid_attributes
        response.should redirect_to(Spider.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved spider as @spider" do
        # Trigger the behavior that occurs when invalid params are submitted
        Spider.any_instance.stub(:save).and_return(false)
        post :create, :spider => {}
        assigns(:spider).should be_a_new(Spider)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Spider.any_instance.stub(:save).and_return(false)
        post :create, :spider => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested spider" do
        spider = Spider.create! valid_attributes
        # Assuming there are no other spiders in the database, this
        # specifies that the Spider created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Spider.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => spider.id, :spider => {'these' => 'params'}
      end

      it "assigns the requested spider as @spider" do
        spider = Spider.create! valid_attributes
        put :update, :id => spider.id, :spider => valid_attributes
        assigns(:spider).should eq(spider)
      end

      it "redirects to the spider" do
        spider = Spider.create! valid_attributes
        put :update, :id => spider.id, :spider => valid_attributes
        response.should redirect_to(spider)
      end
    end

    describe "with invalid params" do
      it "assigns the spider as @spider" do
        spider = Spider.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Spider.any_instance.stub(:save).and_return(false)
        put :update, :id => spider.id.to_s, :spider => {}
        assigns(:spider).should eq(spider)
      end

      it "re-renders the 'edit' template" do
        spider = Spider.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Spider.any_instance.stub(:save).and_return(false)
        put :update, :id => spider.id.to_s, :spider => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested spider" do
      spider = Spider.create! valid_attributes
      expect {
        delete :destroy, :id => spider.id.to_s
      }.to change(Spider, :count).by(-1)
    end

    it "redirects to the spiders list" do
      spider = Spider.create! valid_attributes
      delete :destroy, :id => spider.id.to_s
      response.should redirect_to(spiders_url)
    end
  end

end
