source 'http://rubygems.org'

gem 'rails', '3.1.3'
gem 'paperclip'
gem 'ckeditor_assets'
gem 'rails3-jquery-autocomplete'
#rails g autocomplete:install:install
gem 'gravatar_image_tag', '1.0.0.pre2'




# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'
gem 'simple_form'
gem 'gravatar-ultimate'
gem 'will_paginate', :git => 'git@github.com:bridgeutopia/will_paginate.git', :branch => 'rails3'  
gem 'nifty-generators'
gem 'simple-navigation'
gem 'devise'
gem 'blueprint-rails'
gem 'wirble'
gem 'faker'
gem 'sunspot_rails'
gem 'haml'
#rails g devise:install
#rails g devise User
##rails g devise_views


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.1.4'
  gem 'blueprint-rails'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end
gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

group :test do
  # Pretty printed test output
  gem 'turn', '0.8.2', :require => false
end
gem "mocha", :group => :test
