source 'http://rubygems.org'

gem 'rails', '3.0.9'
gem 'jquery-rails', '>= 1.0.12'
gem 'pry'
# Bundle edge Rails instead:
#gem "transitions", :require => ["transitions", "active_record/transitions"]
gem 'workflow'
gem 'sunspot'
gem 'sunspot_rails'
# gem 'rails', :git => 'git://github.com/rails/rails.git'
gem 'rails3-jquery-autocomplete'

gem 'sqlite3'
gem 'gravatar_image_tag', '1.0.0.pre2'
gem 'will_paginate', '3.0.pre2'
gem 'wirble' # console stuff edit .irbrc
gem 'uuid'
gem 'irt' #improved rails console
gem 'interactive_editor'
gem 'aasm'
gem 'nifty-generators'

group :development do
  gem 'rspec-rails', '2.6.1'
  gem 'ruby-debug19'
  gem 'faker', '0.3.1'
end

group :test do
  gem 'rspec-rails', '2.6.1'
  gem 'webrat', '0.7.1'
  gem 'spork', '0.9.0.rc8'
  gem 'factory_girl_rails','1.0'
end

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger (ruby-debug for Ruby 1.8.7+, ruby-debug19 for Ruby 1.9.2+)
# gem 'ruby-debug'
# gem 'ruby-debug19', :require => 'ruby-debug'

# Bundle the extra gems:
# gem 'bj'
# gem 'nokogiri'
# gem 'sqlite3-ruby', :require => 'sqlite3'
# gem 'aws-s3', :require => 'aws/s3'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
# group :development, :test do
#   gem 'webrat'
# end
