source 'http://rubygems.org'

gem 'rails', '3.1.1'
gem 'rails3-jquery-autocomplete'
gem 'devise'
# rails g devise:install
gem 'will_paginate', :git => 'git@github.com:bridgeutopia/will_paginate.git', :branch => 'rails3'  
gem 'sunspot_rails'
gem 'pusher'
gem 'blueprint-rails'
gem 'em-http-request' # Required by trigger_async
gem 'gravatar-ultimate'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'
gem 'faker'
gem 'wirble'
gem 'gravatar_image_tag', '1.0.0.pre2'



# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.1.4'
  gem 'blueprint-rails'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
 gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
gem 'haml'
gem 'haml-rails', :group => :development
gem 'simple_form'

group :test do
  # Pretty printed test output
  gem 'turn', :require => false
  gem 'rails3-generators' #mainly for factory_girl & simple_form at this point
  gem 'rspec-rails'
  gem 'factory_girl_rails'
end
